apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver-deployment
spec:
  selector:
    matchLabels:
      app: webserver-pod
  replicas: 2
  template:
    metadata:
      name: webserver
      labels:
        app: webserver-pod
    spec:
      containers:
        - name: webserver-container
          image: nginx
